version: '3.8'

services:
  smart-leaf:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./scripts/outputs:/app/scripts/outputs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
